# Generated by Django 5.0.6 on 2024-07-12 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_lastassignedtechnician_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logestadoticket',
            name='estadoticketuser',
            field=models.ForeignKey(db_column='estadoTicketUser', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tecticket',
            name='userasigtecnico',
            field=models.CharField(blank=True, db_column='userAsigTecnico', max_length=255, null=True),
        ),
    ]
