# Generated by Django 5.0.6 on 2024-06-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deptoempresa',
            table='deptoEmpresa',
        ),
        migrations.AlterModelTable(
            name='logestadoticket',
            table='logEstadoTicket',
        ),
        migrations.AlterModelTable(
            name='rolpermiso',
            table='rolPermiso',
        ),
        migrations.AlterModelTable(
            name='tecticket',
            table='tecTicket',
        ),
        migrations.AlterModelTable(
            name='ticketarea',
            table='ticketArea',
        ),
        migrations.AlterModelTable(
            name='tipoticket',
            table='tipoTicket',
        ),
    ]
