# Generated by Django 5.0.6 on 2024-07-10 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userpass',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userfecinivig',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userfecinsercion',
        ),
    ]
