# Generated by Django 5.0.6 on 2024-07-11 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnico',
            name='tecmail',
        ),
    ]
