# Generated by Django 5.0.6 on 2024-07-11 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_tecnico_tecmail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnico',
            name='teccargo',
        ),
    ]
