# Generated by Django 5.0.6 on 2024-07-11 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_tecnico_teccargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='clienteempresadeptoid',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='clientemail',
        ),
        migrations.AddField(
            model_name='cliente',
            name='clienteempresa',
            field=models.ForeignKey(db_column='empresaid', default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='app.empresa'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Deptoempresa',
        ),
    ]
