# Generated by Django 5.0.6 on 2024-07-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_cliente_clienteempresadeptoid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='tecfecnac',
            field=models.DateField(db_column='tecFecNac'),
        ),
    ]
